### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Mahammad Hajiyev",
    "company": "Mahac MMC",
    "address": "S.Vezirov St.",
    "phone": "+994502411115",
    "email":"mahammadhajiyev4@gmail.com",
    "password":"secret123"
} 

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email":"mahammadhajiyev4@gmail.com",
    "password":"password"
} 


### Get user profile  endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haGFtbWFkaGFqaXlldjRAZ21haWwuY29tIiwiaWF0IjoxNjQ0NDk3OTEwLCJleHAiOjE2NDQ0OTg4MTB9._OUGQedeuzsFqiyzNrptzSjOEjnI5TqfnwzKxTa9Q4c


### Tokens router

### Get refreshed token

GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haGFtbWFkaGFqaXlldjRAZ21haWwuY29tIiwiaWF0IjoxNjQ0NjcwMDk4LCJleHAiOjE2NDcyNjIwOTh9.c7cfAqXOjD2-OgpRuBcGAoKZAFRalCSpNR84TJWrRD4



### Pasword reset  request endpoint

POST  http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
   "email": "mahammadhajiyev4@gmail.com"
}


### Update new password endpoint

PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
   "email":"mahammadhajiyev4@gmail.com",
   "pin":"228521",
   "newPassword":"password2"
}