### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Mahammad Hajiyev",
    "company": "Mahac MMC",
    "address": "S.Vezirov St.",
    "phone": "+994502411115",
    "email":"mahammadhajiyev3@gmail.com",
    "password":"secret123"
} 

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email":"mahammadhajiyev3@gmail.com",
    "password":"secret123"
} 

