### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Mahammad Hajiyev",
    "company": "Mahac MMC",
    "address": "S.Vezirov St.",
    "phone": "+994502411115",
    "email":"mahammadhajiyev4@gmail.com",
    "password":"secret123"
} 

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email":"mahammadhajiyev4@gmail.com",
    "password":"secret123"
} 


### Get user profile  endpoint
GET http://localhost:3001/v1/user
Authorisation: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haGFtbWFkaGFqaXlldjRAZ21haWwuY29tIiwiaWF0IjoxNjQ0NDk3OTEwLCJleHAiOjE2NDQ0OTg4MTB9._OUGQedeuzsFqiyzNrptzSjOEjnI5TqfnwzKxTa9Q4c


